server:
  port: ${PORT:8086}
  baseUrl: http://127.0.0.1:${PORT:8086}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://db:3306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Atikokan&useSSL=false&createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root-demo}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

logging:
  level:
    root: INFO
